### ISSUE TITLE
TODO tracker

### ISSUE THREAD

**Issue by kennethnym** [poly-gui/poly-docs#1]
This is an issue tracking to-dos for the documentation:

- [ ] `nanoc`, the codegen tool for NanoPack
- [ ] `nanopack`, the library backing the generated code
  - [ ] C++
  - [ ] Swift
  - [ ] TypeScript
- [ ] Usage for generated code
  - [ ] C++
  - [ ] Swift
  - [ ] TypeScript
- [ ] Supported data types in NanoPack
